osx_image: xcode8.2
language: objective-c
script:
  - set -o pipefail && xcodebuild test -workspace Example/Codice.xcworkspace -scheme Codice-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - bundle exec pod lib lint
